name: test-harness-ariesvcx-ariesvcx
# RUNSET_NAME: "aries-vcx to aries-vcx"
# Scope: AIP 1.0
# Exceptions: None
#
# Summary
#
# This runset uses the current main branch of Aries VCX for all of the agents.
#
# Current
#
# @RFC0793 has some failures due to aries-vcx not supporting full range of DID methods in
# these tests.
# *Status Note Updated: 2024.07.05*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v4
        with:
          path: test-harness
      - name: Docker Login
        uses: azure/docker-login@v2
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        id: run_test_harness
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a aries-vcx"
          TEST_AGENTS: "-d aries-vcx"
          TEST_SCOPE: "-t @RFC0036,@RFC0037,@RFC0160,@RFC0023,@RFC0793 -t ~@wip -t ~@RFC0434 -t ~@RFC0453 -t ~@RFC0211 -t ~@DIDExchangeConnection -t ~@Transport_Ws"
          REPORT_PROJECT: aries-vcx
      - name: run-send-gen-test-results-secure
        if: ${{ steps.run_test_harness.conclusion == 'success' }}
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: aries-vcx
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
